/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#390b00",
        "on-tertiary-container": "#2d2b25",
        "on-primary": "#ffffff",
        "surface-container-low": "#fff1e6",
        "on-secondary-fixed": "#0c2008",
        "inverse-on-surface": "#fdeee2",
        "surface": "#fff8f4",
        "primary-fixed-dim": "#ffb59e",
        "secondary-fixed-dim": "#b4cea8",
        "secondary-fixed": "#d0eac3",
        "background": "#fff8f4",
        "surface-tint": "#99462a",
        "surface-dim": "#e5d8cc",
        "on-surface-variant": "#55433d",
        "on-tertiary": "#ffffff",
        "primary-container": "#d97757",
        "on-secondary-fixed-variant": "#374c2f",
        "inverse-surface": "#372f27",
        "tertiary-container": "#95928a",
        "surface-container": "#faebe0",
        "on-tertiary-fixed": "#1d1c16",
        "tertiary-fixed": "#e7e2d9",
        "on-primary-fixed-variant": "#7a2f15",
        "on-background": "#211a13",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "secondary": "#4e6445",
        "surface-container-high": "#f4e6da",
        "on-secondary": "#ffffff",
        "surface-bright": "#fff8f4",
        "inverse-primary": "#ffb59e",
        "surface-variant": "#eee0d4",
        "outline-variant": "#dbc1b9",
        "surface-container-highest": "#eee0d4",
        "error": "#ba1a1a",
        "primary": "#99462a",
        "on-surface": "#211a13",
        "tertiary": "#615e57",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#cde7c0",
        "on-tertiary-fixed-variant": "#494740",
        "error-container": "#ffdad6",
        "outline": "#88726c",
        "on-primary-container": "#541400",
        "primary-fixed": "#ffdbd0",
        "tertiary-fixed-dim": "#cac6be",
        "on-secondary-container": "#526949"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "unit": "8px",
        "gutter": "24px"
      },
      fontFamily: {
        "display-lg": ["Literata", "serif"],
        "caption": ["Be Vietnam Pro", "sans-serif"],
        "headline-md": ["Literata", "serif"],
        "label-md": ["Be Vietnam Pro", "sans-serif"],
        "headline-lg": ["Literata", "serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        "headline-lg-mobile": ["Literata", "serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "caption": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "34px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }]
      },
    },
  },
  plugins: [],
}
